Added onboarding
xmartlabs/fluttips pull request #46
Opened 2022-12-01 18:06 UTC by SolMendiola

# :star: Feature

---

#### :pencil2: Description:

Added onboarding

---

#### :movie_camera: Screen record:

#### Android

https://user-images.githubusercontent.com/57235692/205127746-119a2c5f-ac00-43f7-9fbd-7dc67ca229ed.mov

---

2022-12-01 18:24 UTC, f7deleon requested changes

2022-12-01 18:24 UTC, f7deleon commented on lib/core/model/enums/onboarding_enum.dart
> +    ' swiping up and down',
check localization for the strings

2022-12-01 18:24 UTC, f7deleon commented on lib/core/repository/session_repository.dart
> +      await _authLocalSource.saveUserToken("authenticate");
why this? we don't have authentication

2022-12-01 18:24 UTC, f7deleon commented on lib/core/source/local_source/auth_local_source.dart
> +    print(_keyToken);
remove and make it arrow

2022-12-01 18:24 UTC, f7deleon commented on lib/ui/onboarding/onboarding_cubit.dart
> +  Future<void> onPressedAction() async {
arrow

2022-12-01 18:24 UTC, f7deleon commented on lib/ui/onboarding/onboarding_cubit.dart
> +  String textButton(int index) => index == 2 ? 'Lets go!' : 'Skip';
localization

2022-12-01 18:24 UTC, f7deleon commented on lib/ui/onboarding/onboarding_cubit.dart
> +  void setCurrentPage(int index) {
arrow

2022-12-01 18:24 UTC, f7deleon commented on lib/ui/onboarding/onboarding_pager.dart
> +  Widget build(BuildContext context) => Stack(
i don't think the stack is needed

2022-12-01 18:24 UTC, f7deleon commented on lib/ui/onboarding/onboarding_pager.dart
> +          PageView(
shouldn't this be constructed by a builder?

2022-12-01 18:24 UTC, f7deleon commented on lib/ui/onboarding/onboarding_pager.dart
> +                          SizedBox(height: 04),
screen utils

2022-12-01 18:24 UTC, f7deleon commented on lib/ui/onboarding/onboarding_screen.dart
> +          );
maybe we can discuss it with @mirland @sante @fedecor9 but I would prefer to use a bloc builder instead of the select. Other than that we have been using bloc builder in the past i think we have to pick one and be consistent with it either we use select or the builders

2022-12-01 18:24 UTC, f7deleon commented on lib/ui/onboarding/onboarding_state.dart
> +    @Default('Start') String buttonText,
should be using localization

2022-12-01 19:43 UTC, mirland requested changes
the asset names should be in snake case (onboarding_describe_app)

2022-12-01 19:43 UTC, mirland commented on lib/ui/onboarding/onboarding_pager.dart
> +                  (e) => Row(
rename the variable

2022-12-01 19:43 UTC, mirland commented on lib/ui/onboarding/onboarding_screen.dart
> +          );
Yes, I agree, I think in this case bloc builder is more clear. Maybe you can change and we can schedule a meeting to talk about that

2022-12-01 19:43 UTC, mirland commented on lib/ui/onboarding/onboarding_pager.dart
> +      BlocBuilder<OnboardingCubit, OnboardingBaseState>(
this will rebuild the pager, I think we shouldn't do that. I'd use the builder only for the dots

2022-12-01 19:43 UTC, mirland commented on lib/ui/onboarding/onboarding_pager.dart
> +  final PageController _pageController;
the controllers have to be declared in a widget with state

2022-12-01 19:43 UTC, mirland commented on lib/ui/onboarding/onboarding_screen.dart
> +                  text: btnText,
maybe remove comma?

2022-12-01 19:43 UTC, mirland commented on lib/ui/onboarding/onboarding_state.dart
> +    @Default(false) bool isStartButtonPressed,
I dont like the name

2022-12-01 19:43 UTC, mirland commented on lib/ui/onboarding/onboarding_state.dart
> +    @Default('Start') String buttonText,
You could maybe use a enum, like onboardingStep, with welcome and onboarding, something like that, so you can "merge" the buttonText and isStartButtonPressed in a enum

2022-12-01 19:43 UTC, mirland commented on pubspec.yaml
> +    - assets/images/
needed?

2022-12-01 19:43 UTC, mirland commented on lib/ui/onboarding/onboarding_start.dart
> +            ),
use codegen and refactor it

2022-12-01 19:43 UTC, mirland commented on lib/ui/onboarding/onboarding_screen.dart
> +    Key? key,
remove comma?

2022-12-01 19:43 UTC, mirland commented on lib/ui/onboarding/onboarding_pager.dart
> +                      ),
one line

2022-12-01 19:43 UTC, mirland commented on lib/ui/onboarding/onboarding_pager.dart
> +    required PageController pageController,
required parameters go first

2022-12-01 19:43 UTC, mirland commented on lib/ui/onboarding/onboarding_screen.dart
> +          );
Also I'd keep the structure of content screen

2022-12-01 19:43 UTC, mirland commented on lib/ui/onboarding/onboarding_pager.dart
> +            children: Onboarding.values
move to a new widger or method

2022-12-01 19:51 UTC, mirland commented on lib/ui/onboarding/onboarding_screen.dart
> +                    : const OnboardingStartScreen(),
if we implement it in this way we will not have the back button. We have to check if it's a problem or not. I'd prever handle the back button

2022-12-01 20:34 UTC, fedecor9 commented on lib/core/model/enums/onboarding_enum.dart
> +  final String secondText;
maybe something like this, since it’s the enhanced enum 
```
  String text(BuildContext context) {
    switch (this) {
      case a:
        return 'A';
      case b:
        return 'B';
    }
  }
```
and we don't need to create an extension

2022-12-01 20:45 UTC, fedecor9 commented on lib/ui/app_router.dart
>        name: 'UnauthenticatedRouter',
I agree, maybe something like OnboardingFlow or something like that

2022-12-13 13:38 UTC, SolMendiola commented on pubspec.yaml
> +    - assets/images/
yes, needed. If i don't put this, when i run the app it broken

2022-12-13 15:39 UTC, mirland commented on lib/core/repository/session_repository.dart
> +  final AuthLocalSource _authLocalSource = DiProvider.get();
you should rename it, maybe SessionLocalSource

2022-12-13 15:39 UTC, mirland commented on lib/core/repository/session_repository.dart
> +  Future<void> setOnboardingState(AppSessionStatus sessionStatus) =>
setSessionStatus

2022-12-13 15:39 UTC, mirland commented on lib/ui/app_router.dart
> +      name: 'UncompletedOnboarding',
Use router suffix, `UncompletedOnboardingRouter`

2022-12-13 15:39 UTC, mirland commented on lib/ui/app_router.dart
> +      name: 'CompletedOnboarding',
`UserOnboardedRouter`?

2022-12-13 15:39 UTC, mirland commented on lib/ui/common/animatedPagerDote.dart
> +  final bool isCurrentPage;
the name is not ok, I mean, the important thing here is fi the dot is selected or not

2022-12-13 15:39 UTC, mirland commented on lib/ui/onboarding/onboarding_button.dart
> +class OnboardingButton extends StatelessWidget {
you should remove it

2022-12-13 15:39 UTC, mirland commented on lib/ui/onboarding/onboarding_cubit.dart
> +            );
we should avoid short assignments in long sentences, I'd use a if sentence here

2022-12-13 15:39 UTC, mirland commented on lib/ui/onboarding/onboarding_cubit.dart
> +  String textButton(int index, BuildContext context) => index == 2
magic number

2022-12-13 15:39 UTC, mirland commented on lib/ui/onboarding/onboarding_start.dart
> +// TODO RENAME FILE
?

2022-12-13 15:39 UTC, mirland commented on lib/ui/onboarding/onboarding_step.dart
> +  onboarding_gestures();
you should use camelcase.

2022-12-13 15:39 UTC, mirland commented on lib/ui/onboarding/onboarding_step.dart
> +  onboarding_gestures();
I think () is not needed

2022-12-13 15:39 UTC, mirland commented on lib/ui/onboarding/onboarding_step.dart
> +      [onboarding_tips_and_tricks, onboarding_favourites, onboarding_gestures];
use values

2022-12-13 15:39 UTC, mirland commented on lib/ui/onboarding/onboarding_step.dart
> +  const OnboardingStep();
needed?

2022-12-13 15:39 UTC, mirland commented on lib/ui/onboarding/onboarding_step.dart
> +        return "Let's go!";
localization

2022-12-13 15:39 UTC, mirland commented on pubspec.yaml
> +    - assets/images/
needed? (I'm not sure, that's why I'm asking )

2022-12-13 15:54 UTC, f7deleon commented on lib/core/source/local_source/auth_local_source.dart
> +  String fromOutput(AppSessionStatus value) => value.name.toString();
its `.toString()` needed if you use `.name`?

2022-12-13 15:54 UTC, f7deleon commented on lib/ui/common/animatedPagerDote.dart
> +        margin: const EdgeInsets.only(left: 4, right: 4, bottom: 15, top: 10),
use screen utils

2022-12-13 15:54 UTC, f7deleon commented on lib/ui/common/border_button.dart
> +            top: 5,
screen utils

2022-12-13 15:54 UTC, f7deleon commented on lib/ui/onboarding/onboarding_button.dart
> +        bottom: 15,
screen utils

2022-12-13 15:54 UTC, f7deleon commented on lib/ui/onboarding/onboarding_cubit.dart
> +  String textButton(int index, BuildContext context) => index == 2
use enum here to get which text you should show

2022-12-13 15:54 UTC, f7deleon commented on lib/ui/onboarding/onboarding_step.dart
> +      [onboarding_tips_and_tricks, onboarding_favourites, onboarding_gestures];
this is a sub set of the onboarding steps since you would not show the first step in the onboarding steps

2022-12-13 17:56 UTC, mirland approved these changes

2022-12-13 18:00 UTC, f7deleon approved these changes

2022-12-13 18:04 UTC, merged