resolve bug with favorites
xmartlabs/fluttips pull request #53
Opened 2022-12-20 19:11 UTC by SolMendiola

# :wrench: Bugfixes

---

#### :pencil2: Description:

Bug fix with favorites navigation 

---

#### :movie_camera: Screen record:

#### iOS

https://user-images.githubusercontent.com/57235692/208747388-b3630e8c-038c-482d-b77a-1981a5fb7047.mov

2022-12-20 19:23 UTC, mirland requested changes

2022-12-20 19:23 UTC, mirland commented on lib/core/repository/tip_repository.dart
> +        tipToUpdate.favouriteDate != null ? null : DateTime.now();
As a rule, try to use the positive way
```suggestion
    tipToUpdate.favouriteDate =
        tipToUpdate.favouriteDate == null ? DateTime.now() : null;
```

2022-12-20 19:23 UTC, mirland commented on lib/ui/favourites/favourites_tips_cubit.dart
> +  Future<void> changeFavouriteButton(Tip tip, int index) async {
I'd the name, maybe toggleFavouriteValue()?

2022-12-20 19:23 UTC, mirland commented on lib/ui/favourites/favourites_tips_cubit.dart
> +    );
why? We shouldn't change it. Also we could have issues, suppose that you have only one element, you will have an out of range issue

2022-12-20 19:23 UTC, mirland commented on lib/ui/tips/tips_cubit.dart
> +    tip = state.tips.elementAt(index);
```suggestion
    tip = state.tips.elementAt(index);
    emit(state.copyWith(currentPage: index));
```

2022-12-20 19:23 UTC, mirland commented on lib/ui/tips/tips_cubit.dart
> +  Future<void> changeFavouriteButton(int index) =>
same, maybe toggleFavouriteTipValue

2022-12-20 19:23 UTC, mirland commented on lib/ui/tips/tips_cubit.dart
> +      _tipRepository.toggleFavouriteTip(state.tips[index]);
do you need the index? because you have the current tip in this cubit

2022-12-21 10:23 UTC, SolMendiola commented on lib/ui/tips/tips_cubit.dart
> +      _tipRepository.toggleFavouriteTip(state.tips[index]);
I can't use the tip here because i only set the tip in favourite screen but in the screen for all tips this tip is null. But i can use the current page and delete the index parameter

2022-12-21 12:51 UTC, mirland commented on lib/ui/tips/tips_cubit.dart
> +      _tipRepository.toggleFavouriteTip(state.tips[index]);
But we should be consistent, we have two options, 
1. we change the tip when the page change
2. We dont change the tip when the page change and we rename the variable _tip to _initialTip

I think both solutions are valid, but we should be consistent

2022-12-21 12:53 UTC, mirland commented on lib/ui/favourites/favourites_tips_cubit.dart
> +    );
Remember this question

2022-12-21 21:05 UTC, mirland approved these changes

2022-12-21 21:05 UTC, mirland commented on lib/ui/tips/tips_state.dart
> +    Tip? currentTip,
do we need it? I think we are not using it

2022-12-21 21:16 UTC, fedecor9 commented on lib/ui/tips/tips_state.dart
> +    Tip? currentTip,
It was already un use, it's the tip variable that was used i'm the cubit. we added it to the state because it was being updated manually when the state changed and because of that there was a bug with the favorite tip being outdated with the one in the state that currentPage refered to

2022-12-22 12:32 UTC, merged

2022-12-22 13:25 UTC, mirland commented on lib/ui/tips/tips_state.dart
> +    Tip? currentTip,
Yes, but this tip is using internally by the cubit, so it shouldn't be in the state.
The state should contain the info that you need for drawing, in this case you are not using it for drawing.
In this case it's pretty the same, because the index and the tip are related, but in other case it could generate unnecessary redraws

2022-12-22 14:25 UTC, fedecor9 commented on lib/ui/tips/tips_state.dart
> +    Tip? currentTip,
Mmm It makes sense, for now, since we are emitting at the same time it doesn’t affect anything, but as you say, in the future it could trigger unnecessary redraws for nothing. The main reason for adding it was because it was being updated at the same time as the state, and having to update both at the same time was a bit tedious and prone to error. 
Limiting the build method, so it doesn’t build when current tip changes wouldn’t help solve the redraws?