feature:  add about app
xmartlabs/fluttips pull request #58
Opened 2022-12-29 19:46 UTC by SolMendiola

# :star: Feature

---

#### :pencil2: Description:

Added about app

---

#### :movie_camera: Screen record:

#### iOS

https://user-images.githubusercontent.com/57235692/210004554-09f7a3cc-72e9-4017-b7a7-8c763f8178a9.mov

![IMG_1273](https://user-images.githubusercontent.com/57235692/210004496-8c670baa-10b0-4ac2-9d9f-bb71057afe6d.PNG)

2022-12-30 04:07 UTC, mirland requested changes

2022-12-30 04:07 UTC, mirland commented on lib/ui/about/about_webview_screen.dart
> +class AboutWebViewScreen extends StatelessWidget {
you can create a WebViewScreen and add the file path as a arameter

2022-12-30 04:07 UTC, mirland commented on lib/ui/about/about_webview_screen.dart
> +                onPressed: () => context.read<AboutCubit>().navigateToAbout(),
you should navigate back, instead of a new screen

2022-12-30 04:07 UTC, mirland commented on lib/ui/home/drawer.dart
> +                .where((element) => element.index != 3)
magic number! use HomeNavOptions info

2022-12-30 04:07 UTC, mirland commented on lib/ui/home/drawer.dart
> +                  isCurrentIndex: 3 == _tabsController.activeIndex,
magic number

2022-12-30 04:07 UTC, mirland commented on web_privacy_policy/public/terms_and_conditions.html
> +</html>
```suggestion
</html>

```

2022-12-30 04:07 UTC, mirland commented on assets/policy_and_terms/terms_and_conditions.html
> +</html>
```suggestion
</html>

```

2022-12-30 04:07 UTC, mirland commented on lib/l10n/intl_en.arb
> +  "button_privacy": "Privacy policy",
same for other cases

2022-12-30 04:07 UTC, mirland commented on lib/ui/about/about_cubit.dart
> +  void navigateToAbout() => _router.navigate(const AboutScreenRoute());
dont need it

2022-12-30 04:07 UTC, mirland commented on lib/ui/about/about_screen.dart
> +class SuggestionSection extends StatelessWidget {
all internal sections should be private

2022-12-30 04:07 UTC, mirland commented on lib/ui/about/about_webview_screen.dart
> +class AboutWebViewScreen extends StatelessWidget {
If you do that, move this file to another package

2022-12-30 04:07 UTC, mirland commented on lib/ui/about/about_webview_screen.dart
> +  late final bool _isPrivacyPolicy;
why not in the constructor?

2022-12-30 16:25 UTC, mirland commented on lib/l10n/intl_en.arb
> +  "email_subject": "Feedback: app version ",
Yo should add the app version as a param here, check the error string

2022-12-30 16:25 UTC, mirland commented on lib/l10n/intl_en.arb
> +  "email_subject": "Feedback: app version ",
Maybe feedback_email_subject

2022-12-30 16:25 UTC, mirland commented on lib/ui/about/about_cubit.dart
> +import 'package:fluttips/ui/common/context_extensions.dart';
Remove the unnecessary spaces

2022-12-30 16:25 UTC, mirland commented on lib/ui/about/about_cubit.dart
> +  final AppRouter _router = DiProvider.get();
Injections have to me defined before the constructor fields

2022-12-30 16:25 UTC, mirland commented on lib/ui/about/about_screen.dart
> +class AboutContentScreen extends StatelessWidget {
Private?

2022-12-30 16:25 UTC, mirland commented on lib/ui/home/drawer.dart
> +                .where((element) => element.index != 3)
You shouldn't hardcore the number

2022-12-30 16:25 UTC, mirland commented on lib/ui/webView/webview_screen.dart
> +                onPressed: () => _action(),
Shouldn't you navigate just back? Do you need the action?

2022-12-30 16:25 UTC, mirland commented on lib/ui/webView/webview_screen.dart
> +  _WebViewScreenState();
Same question, why not use the params like path in the constructor?

2022-12-30 16:25 UTC, mirland commented on pubspec.yaml
> +  package_info_plus: ^3.0.2
Sort and remove the hat

2022-12-30 16:25 UTC, mirland commented on lib/ui/about/about_cubit.dart
> +  Future<void> sendEmail(BuildContext context) async {
I would not send the context here, it's a cubit. I'd use the Resources class

2022-12-30 16:25 UTC, mirland commented on lib/ui/about/about_screen.dart
> +                .navigateToWebView(Assets.policyAndTerms.termsAndConditions),
I'd manage the path in the cubit

2022-12-30 16:25 UTC, mirland commented on lib/ui/about/about_screen.dart
> +                .navigateToWebView(Assets.policyAndTerms.privacyPolicy),
Same

2023-01-03 16:14 UTC, SolMendiola commented on lib/ui/webView/webview_screen.dart
> +  _WebViewScreenState();
If I put path as a parameter, the linter throws an error in the createState

2023-01-03 16:31 UTC, gfran93 approved these changes
Well done!

2023-01-03 16:31 UTC, gfran93 commented on lib/ui/about/about_cubit.dart
> +  void navigateToWebView({required bool isPrivacyPolicy}) => _router.navigate(
I don't think this is wrong. But in my opinion, you're giving too much responsibility to the view. I'd take a different approach:

I'd add on the About cubit two methods:

* onTermsAndConditionsButtonPressed()
* onPrivacyPolicyButtonPressed()

(sticking to the naming convention that you're using in the project)

The UI would call these methods, and the cubit would handle the different routes. Doing this, you deliver the responsibility to the cubit. And here not only would it handle navigation, but also in the future it may save analytics or other stuff like that.

What do you think?

2023-01-03 16:31 UTC, gfran93 commented on lib/ui/about/about_screen.dart
> +                .navigateToWebView(isPrivacyPolicy: false),
this is where i would change it on the screen

2023-01-03 16:31 UTC, gfran93 commented on lib/ui/about/about_screen.dart
> +                .navigateToWebView(isPrivacyPolicy: true),
same

2023-01-03 16:31 UTC, gfran93 commented on lib/ui/webView/webview_screen.dart
> +      margin: EdgeInsets.only(left: 45, top: 10.h),
units?

2023-01-03 16:31 UTC, gfran93 commented on lib/ui/webView/webview_screen.dart
> +  late final String _path;
in my opinion, it is not necessary. You define the field, assign it and use it once (at ln 27)

2023-01-03 16:31 UTC, gfran93 commented on web_privacy_policy/public/terms_and_conditions.html
> +</html>
new line?

2023-01-04 17:23 UTC, mirland approved these changes

2023-01-04 17:23 UTC, mirland commented on lib/ui/about/about_cubit.dart
> +          Resources.localizations.app_version +
Use string interpolation in the same string, in resources

2023-01-04 17:23 UTC, mirland commented on pubspec.yaml
> +  package_info_plus: 3.0.2
Alpha

2023-01-10 16:14 UTC, merged