Added readme
xmartlabs/fluttips pull request #66
Opened 2023-01-16 18:57 UTC by SolMendiola

# :star: Feature

---

#### :pencil2: Description:

Added readme

---

2023-01-17 20:12 UTC, ValentinaBianco requested changes
Readme changes

2023-01-17 20:12 UTC, ValentinaBianco commented on README.md
> +It provides different sections, for example, you can see images with code explications and if you like, you can save the tip to see it later in favorites section.
```suggestion
Some of its features include images and code explanations, making it easy to understand the tips provided.
Additionally, users can save their favorite tips to a "favorites" section, allowing them to easily access them later.
```

2023-01-17 20:12 UTC, ValentinaBianco commented on README.md
> +In a coming soon version, you will see videos of the widgets of the week, that provides you information about different components of Flutter.
```suggestion
In an upcoming version, you will be able to view "Widget of the Week" videos, which will provide you with detailed information about various elements of Flutter.
```

2023-01-17 20:12 UTC, ValentinaBianco commented on README.md
> +The application was made with love by [Xmartlabs][xmartlabs] team and Fluttips is based on [Xmartlabs template][xmartlabs_template], which provides a clean architecture.
```suggestion
Made with ❤️ by [Xmartlabs][xmartlabs] and based on [our template][xmartlabs_template], which provides a clean architecture.
```

2023-01-17 20:12 UTC, ValentinaBianco commented on README.md
> +The images tips are from [Vandadnp][Vandadnp]
```suggestion
👉 The image tips are from [Vandadnp][Vandadnp]
```

2023-01-17 20:12 UTC, ValentinaBianco commented on README.md
```suggestion
👉 If you enjoy using **Fluttips** we would love to hear about it! Drop us a line on [twitter](https://twitter.com/xmartlabs).
```

2023-01-18 15:00 UTC, mirland commented on README.md
> +👉 The videos are from [Widgets of the week][Widget_of_the_week].
check the preview but new lines are missing

2023-01-18 15:00 UTC, mirland commented on README.md
> +  👉 If you **have a feature request** please **open an issue**.
link to new issue

2023-01-18 15:00 UTC, mirland commented on README.md
> +  👉 If you enjoy using **Fluttips** we would love to hear about it! Drop us a line on [twitter](https://twitter.com/xmartlabs).
ref?

2023-01-19 14:52 UTC, mirland commented on README.md
> +<img src="readme/Favorites.gif" width="250"/>
what about adding both in the same row?

2023-01-19 14:52 UTC, mirland commented on README.md
> +# Fluttips
We should add a banner with the logo

2023-01-19 14:52 UTC, mirland commented on README.md
include badges

2023-01-19 14:52 UTC, mirland commented on README.md
> +<img src="readme/Favorites.gif" width="250"/>
what about adding both in the same row?

2023-01-19 14:52 UTC, mirland commented on README.md
> +  👉 If you **found a bug** or **need help** please let us know.
how? maybe a link

2023-01-19 19:02 UTC, ValentinaBianco submitted a review, later dismissed
small changes to readme

2023-01-19 22:45 UTC, mirland requested changes

2023-01-19 22:45 UTC, mirland commented on README.md
> +<img src="readme/Fluttips_logo.png" width=“100%”/>
the image does not fit in the screen
![image](https://user-images.githubusercontent.com/8472881/213578443-bb4242ac-4aef-45f3-a94f-3fd9d5eed670.png)

2023-01-19 22:45 UTC, mirland commented on README.md
> +## Introduction
Do we need this title?

2023-01-19 22:45 UTC, mirland commented on README.md
> +<img src="readme/Images.gif" width=“500”/> <img src="readme/Favorites.gif" width="500"/>
the image does not look well 
![image](https://user-images.githubusercontent.com/8472881/213578589-565d6bf9-bfb5-475b-9d28-7193b21d04c8.png)

2023-01-19 22:45 UTC, mirland commented on README.md
license should be added here

2023-01-19 22:45 UTC, mirland commented on README.md
> +<img src="readme/Images.gif" width=“500”/> <img src="readme/Favorites.gif" width="500"/>
images shouldn't say debug

2023-01-19 22:45 UTC, mirland commented on README.md
> +<img src="readme/Fluttips_logo.png" width=“100%”/>
I'm not sure about the folder, what about /docs/assets?

2023-01-23 14:55 UTC, merged