feat: Added clean data
xmartlabs/fluttips pull request #68
Opened 2023-01-17 16:21 UTC by SolMendiola

# :star: Feature

---

#### :pencil2: Description:

Added clean data

---

2023-01-17 19:08 UTC, f7deleon commented on lib/core/common/config.dart
> +  static String key = 'alreadyCleanData';
maybe a more descriptive key like `alreadyCleanDataKey`

2023-01-17 19:08 UTC, f7deleon commented on lib/main.dart
> +  if (!(prefs.getBool(Config.key) != null)) {
this checks for the key to be nullable i think that are two separate conditions or check directly the value you are expecting like `false`

2023-01-17 22:40 UTC, mirland commented on lib/core/common/config.dart
> +  static String key = 'alreadyCleanData';
it shouldnt be in the config right?

2023-01-17 22:44 UTC, mirland approved these changes

2023-01-17 22:44 UTC, mirland commented on lib/core/common/config.dart
> +  static String key = 'alreadyCleanData';
It shouldn't be in the config right?

2023-01-17 22:44 UTC, mirland commented on lib/main.dart
> +  if (!(prefs.getBool(Config.key) != null)) {
why not just `!prefs.getBool(Config.key) == true`?

2023-01-17 22:44 UTC, mirland commented on lib/main.dart
> +  final SharedPreferences prefs = await SharedPreferences.getInstance();
I'd use a provider, lets discuss it tomorrow, but we can follow [this pr](https://github.com/xmartlabs/flutter-template/pull/124)

2023-01-17 22:44 UTC, mirland commented on pubspec.yaml
> +  shared_preferences: ^2.0.16
alpha and hat

2023-01-17 22:44 UTC, mirland commented on lib/main.dart
> +    const FlutterSecureStorage storage = FlutterSecureStorage();
you are not injecting it

2023-01-17 22:45 UTC, mirland requested changes
Let check the comments before merge it

2023-01-18 18:00 UTC, mirland approved these changes

2023-01-18 18:00 UTC, mirland commented on lib/core/common/config.dart
>    static const debugMode = kDebugMode;
I'd keep this line
```suggestion

  static const debugMode = kDebugMode;
```

2023-01-18 18:00 UTC, mirland commented on lib/core/di/di_utils_module.dart
> +      () => $FloorAppDatabase.databaseBuilder('database.db').build(),
we can maybe add the DB name in the config file

2023-01-18 20:23 UTC, merged